# 모델링

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
import matplotlib as mpl
from datetime import datetime
from datetime import timedelta

# Windows
mpl.rc("font", family='Malgun Gothic')

warnings.filterwarnings("ignore")
%matplotlib inline
%config InlineBackend.figure_format='retina'

In [2]:
csv_EDA = 'C:/Users/JEON_SANGEON/codestates/data/cp2_EDA.csv'
rating = 'C:/Users/JEON_SANGEON/codestates/data/view_rating.csv'

df_EDA= pd.read_csv(csv_EDA)

In [3]:
df_rating = pd.read_csv(rating)

In [4]:
# csv 불러와서 날짜컬럼 재설정
df_EDA['event_time'] = pd.to_datetime(df_EDA['event_time'], utc=True)
df_EDA['event_time'] = df_EDA['event_time'].dt.tz_convert('Asia/Dubai')

In [5]:
# 불필요 컬럼 제거
del df_EDA['Unnamed: 0']

In [6]:
df_EDA = df_EDA.loc[(df_EDA['price']!=0)]

In [7]:
df = df_EDA.copy()

In [8]:
del df_rating['Unnamed: 0']

df_rating

           user_id        category_code     value
0        265601964      accessories.bag  0.142857
1        301823874      accessories.bag  0.083333
2        338504180      accessories.bag  1.000000
3        388529847      accessories.bag  0.250000
4        414404621      accessories.bag  0.666667
...            ...                  ...       ...
6989139  566109860  stationery.cartrige  1.000000
6989140  566122879  stationery.cartrige  1.000000
6989141  566127538  stationery.cartrige  1.000000
6989142  566132392  stationery.cartrige  0.333333
6989143  566211779  stationery.cartrige  0.176471

[6989144 rows x 3 columns]

In [9]:
df_view = df.loc[df['event_type']=='view']

In [10]:
# merge

df = pd.merge(left=df_view, right=df_rating,how='left',\
                    on=['user_id','category_code'],sort=False)

In [11]:
df

,event_time,month,day,day_name,hour,event_type,product_id,category_id,category_code,brand,price,user_id,user_session,value
0,2019-10-01 04:00:00+04:00,10,1,Tuesday,4,view,44600062,2103807459595387724,no_cat,shiseido,35.79,541312140,72d76fde-8bb3-4e00-8c23-a032dfed738c,0.672000
1,2019-10-01 04:00:00+04:00,10,1,Tuesday,4,view,3900821,2053013552326770905,appliances.environment.water_heater,aqua,33.20,554748717,9333dfbd-b87a-4708-9857-6336556b0fcc,1.000000
2,2019-10-01 04:00:01+04:00,10,1,Tuesday,4,view,17200506,2053013559792632471,furniture.living_room.sofa,no_brand,543.10,519107250,566511c2-e2e3-422b-b695-cf8e6e792ca8,0.047619
3,2019-10-01 04:00:01+04:00,10,1,Tuesday,4,view,1307067,2053013558920217191,computers.notebook,lenovo,251.74,550050854,7c90fc70-0e80-4590-96f3-13c02c18c713,0.318182
4,2019-10-01 04:00:04+04:00,10,1,Tuesday,4,view,1004237,2053013555631882655,electronics.smartphone,apple,1081.98,535871217,c6bd7419-2748-4c56-95b4-8cec9ff8b80d,0.306818
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40710871,2019-11-01 03:59:58+04:00,11,1,Friday,3,view,2300275,2053013560530830019,electronics.camera.video,gopro,527.40,537931532,22c57267-da98-4f28-9a9c-18bb5b385193,0.147059
40710872,2019-11-01 03:59:58+04:00,11,1,Friday,3,view,10800172,2053013554994348409,appliances.kitchen.multibaker,redmond,61.75,527322328,5054190a-46cb-4211-a8f1-16fc1a060ed8,0.081967
40710873,2019-11-01 03:59:58+04:00,11,1,Friday,3,view,5701038,2053013553970938175,auto.accessories.player,kenwood,128.70,566280422,05b6c62b-992f-4e8e-91f7-961bcb4719cd,1.000000
40710874,2019-11-01 03:59:59+04:00,11,1,Friday,3,view,21407424,2053013561579406073,electronics.clocks,tissot,689.85,513118352,4c14bf2a-2820-4504-929d-046356a5a204,0.565217
40710875,2019-11-01 03:59:59+04:00,11,1,Friday,3,view,13300120,2053013557166998015,furniture.bedroom.mattress,swisshome,155.73,525266378,6e57d2d7-6022-46e6-81d6-fa77f14cefd8,0.080000

참조 : 
https://github.com/journey101/Recommendation_CF_Hybrid_Modeling_with_Python_Surprise/blob/main/Recommendation_CF_Hybrid_modeling_for_Fashion_update(210621).ipynb

In [10]:
df

,event_time,month,day,day_name,hour,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2019-10-01 04:00:00+04:00,10,1,Tuesday,4,view,44600062,2103807459595387724,no_cat,shiseido,35.79,541312140,72d76fde-8bb3-4e00-8c23-a032dfed738c
1,2019-10-01 04:00:00+04:00,10,1,Tuesday,4,view,3900821,2053013552326770905,appliances.environment.water_heater,aqua,33.20,554748717,9333dfbd-b87a-4708-9857-6336556b0fcc
2,2019-10-01 04:00:01+04:00,10,1,Tuesday,4,view,17200506,2053013559792632471,furniture.living_room.sofa,no_brand,543.10,519107250,566511c2-e2e3-422b-b695-cf8e6e792ca8
3,2019-10-01 04:00:01+04:00,10,1,Tuesday,4,view,1307067,2053013558920217191,computers.notebook,lenovo,251.74,550050854,7c90fc70-0e80-4590-96f3-13c02c18c713
4,2019-10-01 04:00:04+04:00,10,1,Tuesday,4,view,1004237,2053013555631882655,electronics.smartphone,apple,1081.98,535871217,c6bd7419-2748-4c56-95b4-8cec9ff8b80d
...,...,...,...,...,...,...,...,...,...,...,...,...,...
42448759,2019-11-01 03:59:58+04:00,11,1,Friday,3,view,2300275,2053013560530830019,electronics.camera.video,gopro,527.40,537931532,22c57267-da98-4f28-9a9c-18bb5b385193
42448760,2019-11-01 03:59:58+04:00,11,1,Friday,3,view,10800172,2053013554994348409,appliances.kitchen.multibaker,redmond,61.75,527322328,5054190a-46cb-4211-a8f1-16fc1a060ed8
42448761,2019-11-01 03:59:58+04:00,11,1,Friday,3,view,5701038,2053013553970938175,auto.accessories.player,kenwood,128.70,566280422,05b6c62b-992f-4e8e-91f7-961bcb4719cd
42448762,2019-11-01 03:59:59+04:00,11,1,Friday,3,view,21407424,2053013561579406073,electronics.clocks,tissot,689.85,513118352,4c14bf2a-2820-4504-929d-046356a5a204
42448763,2019-11-01 03:59:59+04:00,11,1,Friday,3,view,13300120,2053013557166998015,furniture.bedroom.mattress,swisshome,155.73,525266378,6e57d2d7-6022-46e6-81d6-fa77f14cefd8

In [13]:
item_ = df.groupby(by='product_id').count()
item_

,event_time,month,day,day_name,hour,event_type,category_id,category_code,brand,price,user_id,user_session
product_id,,,,,,,,,,,,
1000978,3094,3094,3094,3094,3094,3094,3094,3094,3094,3094,3094,3094
1001588,2276,2276,2276,2276,2276,2276,2276,2276,2276,2276,2276,2276
1001606,16,16,16,16,16,16,16,16,16,16,16,16
1002042,328,328,328,328,328,328,328,328,328,328,328,328
1002062,1574,1574,1574,1574,1574,1574,1574,1574,1574,1574,1574,1574
...,...,...,...,...,...,...,...,...,...,...,...,...
60500005,14,14,14,14,14,14,14,14,14,14,14,14
60500006,14,14,14,14,14,14,14,14,14,14,14,14
60500007,11,11,11,11,11,11,11,11,11,11,11,11
60500009,4,4,4,4,4,4,4,4,4,4,4,4
60500010,10,10,10,10,10,10,10,10,10,10,10,10

In [14]:
user_ = df.groupby(by='user_id').count()
user_

,event_time,month,day,day_name,hour,event_type,product_id,category_id,category_code,brand,price,user_session
user_id,,,,,,,,,,,,
33869381,1,1,1,1,1,1,1,1,1,1,1,1
183503497,1,1,1,1,1,1,1,1,1,1,1,1
184265397,6,6,6,6,6,6,6,6,6,6,6,6
195082191,1,1,1,1,1,1,1,1,1,1,1,1
200673532,4,4,4,4,4,4,4,4,4,4,4,4
...,...,...,...,...,...,...,...,...,...,...,...,...
566280663,2,2,2,2,2,2,2,2,2,2,2,2
566280676,1,1,1,1,1,1,1,1,1,1,1,1
566280697,1,1,1,1,1,1,1,1,1,1,1,1
566280780,1,1,1,1,1,1,1,1,1,1,1,1
566280860,1,1,1,1,1,1,1,1,1,1,1,1

In [15]:
user_.sort_values(by="product_id", ascending=False)

,event_time,month,day,day_name,hour,event_type,product_id,category_id,category_code,brand,price,user_session
user_id,,,,,,,,,,,,
512475445,7429,7429,7429,7429,7429,7429,7429,7429,7429,7429,7429,7429
512365995,4012,4012,4012,4012,4012,4012,4012,4012,4012,4012,4012,4012
526731152,2912,2912,2912,2912,2912,2912,2912,2912,2912,2912,2912,2912
512505687,2894,2894,2894,2894,2894,2894,2894,2894,2894,2894,2894,2894
513021392,2862,2862,2862,2862,2862,2862,2862,2862,2862,2862,2862,2862
...,...,...,...,...,...,...,...,...,...,...,...,...
554255592,1,1,1,1,1,1,1,1,1,1,1,1
554255594,1,1,1,1,1,1,1,1,1,1,1,1
554255636,1,1,1,1,1,1,1,1,1,1,1,1
554255639,1,1,1,1,1,1,1,1,1,1,1,1
566280860,1,1,1,1,1,1,1,1,1,1,1,1

In [16]:
df.groupby(by='category_code').count()

,event_time,month,day,day_name,hour,event_type,product_id,category_id,brand,price,user_id,user_session
category_code,,,,,,,,,,,,
accessories.bag,190017,190017,190017,190017,190017,190017,190017,190017,190017,190017,190017,190017
accessories.jewelry,1672378,1672378,1672378,1672378,1672378,1672378,1672378,1672378,1672378,1672378,1672378,1672378
accessories.umbrella,3923,3923,3923,3923,3923,3923,3923,3923,3923,3923,3923,3923
accessories.wallet,43476,43476,43476,43476,43476,43476,43476,43476,43476,43476,43476,43476
apparel.belt,2429,2429,2429,2429,2429,2429,2429,2429,2429,2429,2429,2429
...,...,...,...,...,...,...,...,...,...,...,...,...
sport.ski,3005,3005,3005,3005,3005,3005,3005,3005,3005,3005,3005,3005
sport.snowboard,3727,3727,3727,3727,3727,3727,3727,3727,3727,3727,3727,3727
sport.tennis,3540,3540,3540,3540,3540,3540,3540,3540,3540,3540,3540,3540
sport.trainer,35803,35803,35803,35803,35803,35803,35803,35803,35803,35803,35803,35803
stationery.cartrige,7540,7540,7540,7540,7540,7540,7540,7540,7540,7540,7540,7540

product_id별 user_id : 1:n관계 \
user_id별 product_id : 1:n관계 \
category_code 별 product_id : 1:n관계 

추천 시스템에 적용하기에 적합한 데이터로 판단됨. (유사 유저그룹 판단 후 아직 경험하지 않은 아이템을 추천해야 하기 때문)

In [12]:
df = df.head(100000)

# 아래는 원본 데이터로 진행된 내용

In [13]:
# rating을 value로 놓고 진행함.


mean_df = df[['product_id','value']].groupby(by='product_id').mean()
mean_df = mean_df.reset_index()
mean_df = mean_df.rename(columns={'value': 'rating_average'})
mean_df

       product_id  rating_average
0         1001588        0.815028
1         1002062        1.000000
2         1002098        0.719937
3         1002099        0.768884
4         1002100        0.659242
...           ...             ...
20910    52900101        0.141447
20911    53100005        0.090909
20912    53100006        0.176471
20913    53100013        0.155738
20914    53100015        0.086957

[20915 rows x 2 columns]

In [14]:
df_r_m = pd.merge(df, mean_df, how='left', on='product_id')
df_r_m['user_id'] = df_r_m['user_id'].astype(int)
df_r_m['product_id'] = df_r_m['product_id'].astype(int)
# df_r_merge.dtypes

df_r_m.head()

,event_time,month,day,day_name,hour,event_type,product_id,category_id,category_code,brand,price,user_id,user_session,value,rating_average
0,2019-10-01 04:00:00+04:00,10,1,Tuesday,4,view,44600062,2103807459595387724,no_cat,shiseido,35.79,541312140,72d76fde-8bb3-4e00-8c23-a032dfed738c,0.672000,0.672000
1,2019-10-01 04:00:00+04:00,10,1,Tuesday,4,view,3900821,2053013552326770905,appliances.environment.water_heater,aqua,33.20,554748717,9333dfbd-b87a-4708-9857-6336556b0fcc,1.000000,0.265464
2,2019-10-01 04:00:01+04:00,10,1,Tuesday,4,view,17200506,2053013559792632471,furniture.living_room.sofa,no_brand,543.10,519107250,566511c2-e2e3-422b-b695-cf8e6e792ca8,0.047619,0.463999
3,2019-10-01 04:00:01+04:00,10,1,Tuesday,4,view,1307067,2053013558920217191,computers.notebook,lenovo,251.74,550050854,7c90fc70-0e80-4590-96f3-13c02c18c713,0.318182,0.692627
4,2019-10-01 04:00:04+04:00,10,1,Tuesday,4,view,1004237,2053013555631882655,electronics.smartphone,apple,1081.98,535871217,c6bd7419-2748-4c56-95b4-8cec9ff8b80d,0.306818,0.753152

In [23]:
df_r_m.dtypes

event_time        datetime64[ns, Asia/Dubai]
month                                  int64
day                                    int64
day_name                              object
hour                                   int64
event_type                            object
product_id                             int32
category_id                            int64
category_code                         object
brand                                 object
price                                float64
user_id                                int32
user_session                          object
value                                float64
rating_average                       float64
dtype: object

In [25]:
df_r_m['value'].value_counts()

1.000000    7353892
0.500000     737370
0.333333     480161
0.666667     468136
0.250000     358332
             ...
0.001715          1
0.000455          1
0.001131          1
0.000904          1
0.001812          1
Name: value, Length: 33765, dtype: int64

# 모델 분석방법

surprise 모듈 임포트

In [15]:
from surprise import SVD, BaselineOnly, SVDpp, Reader
from surprise import Dataset
from surprise.model_selection import cross_validate
from surprise.prediction_algorithms import KNNBaseline
from surprise import accuracy
from surprise import dump
from sklearn.metrics.pairwise import linear_kernel, cosine_similarity

In [16]:
# train, test set split 

## data randomly shuffling.  
df_r_m = df_r_m.sample(frac=1)
df_r_m

len(df_r_m)
cutoff = int(.5 * len(df_r_m))
train_r = df_r_m[:cutoff]
test_r = df_r_m[cutoff:]

train_r = train_r[['user_id', 'product_id', 'value', 'category_code', 'brand']]
test_r = test_r[['user_id', 'product_id', 'value', 'category_code', 'brand']]
print("train_size:", len(train_r), "test_size:", len(test_r))
train_r.head()

train_size: 50000 test_size: 50000

,user_id,product_id,value,category_code,brand
97490,548707010,4100214,0.062500,electronics.video.tv,nintendo
50677,513414569,3601437,0.128492,appliances.kitchen.dishwasher,lg
88266,514534397,6200978,0.099391,appliances.environment.air_heater,no_brand
63027,513033464,26000565,0.833333,missing,missing
62696,549395480,17200570,0.875000,furniture.living_room.sofa,no_brand

In [17]:
def convert_traintest_dataframe_forsurprise(training_dataframe, testing_dataframe):
    reader = Reader(rating_scale=(0, 5))
    trainset = Dataset.load_from_df(training_dataframe[['user_id', 'product_id', 'value']], reader)
    testset = Dataset.load_from_df(testing_dataframe[['user_id', 'product_id', 'value']], reader)
    
    trainset = trainset.construct_trainset(trainset.raw_ratings)
    testset = testset.construct_testset(testset.raw_ratings)
    
    return trainset, testset

In [18]:

trainset, testset = convert_traintest_dataframe_forsurprise(train_r, test_r)

## (1) Knn-baseline 모델

In [19]:
# basic collaborative filtering algorithm taking into account a baseline rating.
# content-based filtering (CBF)
# 참조: https://surprise.readthedocs.io/en/stable/knn_inspired.html

sim_options = {'name': 'cosine',
               'user_based': False  # content(item)-based similarity
               }
knnbaseline_algo_i = KNNBaseline(sim_options=sim_options)

knnbaseline_algo_i.fit(trainset)
knnbaseline_predictions_i = knnbaseline_algo_i.test(testset)

file_name = 'KnnBaseline_model_i'
dump.dump(file_name, algo=knnbaseline_predictions_i)
# _, loaded_algo = dump.load(file_name)

accuracy.rmse(knnbaseline_predictions_i)
accuracy.mae(knnbaseline_predictions_i)
print("Done!")

Estimating biases using als...
Computing the cosine similarity matrix...
Done computing similarity matrix.
RMSE: 0.2211
MAE:  0.1529
Done!

In [20]:
# basic collaborative filtering algorithm taking into account a baseline rating.
# user-based filtering (CBF)
# 참조: https://surprise.readthedocs.io/en/stable/knn_inspired.html

sim_options = {'name': 'cosine',
               'user_based': True  # user-based similarity
               }
knnbaseline_algo_u = KNNBaseline(sim_options=sim_options)

knnbaseline_algo_u.fit(trainset)
knnbaseline_predictions_u = knnbaseline_algo_u.test(testset)

file_name = 'KnnBaseline_model_u'
dump.dump(file_name, algo=knnbaseline_predictions_u)
# _, loaded_algo = dump.load(file_name)

accuracy.rmse(knnbaseline_predictions_u)
accuracy.mae(knnbaseline_predictions_u)
print("Done!")

Estimating biases using als...
Computing the cosine similarity matrix...
Done computing similarity matrix.
RMSE: 0.2673
MAE:  0.2143
Done!

In [21]:
knnbaseline_predictions_i = knnbaseline_algo_i.test(testset)
knnbaseline_predictions_i[:3]

[Prediction(uid=544371892, iid=22700067, r_ui=0.2333333333333333, est=0.2059819315766458, details={'actual_k': 3, 'was_impossible': False}),
 Prediction(uid=515122879, iid=5100567, r_ui=0.1304347826086956, est=0.5553483785315021, details={'actual_k': 0, 'was_impossible': False}),
 Prediction(uid=514680524, iid=4200882, r_ui=1.0, est=0.5594184235648336, details={'was_impossible': False})]

In [22]:
# uid, iid, r_ui(실제 평점) ,est(예측평점) 추출

[(pred.uid, pred.iid, pred.est) for pred in knnbaseline_predictions_i[:3]]

[(544371892, 22700067, 0.2059819315766458),
 (515122879, 5100567, 0.5553483785315021),
 (514680524, 4200882, 0.5594184235648336)]

In [24]:
# uid = 998923 에 대한 유사도 높은 예측 iid, est 조회. 
# 참고: https://hmkim312.github.io/posts/%EC%84%9C%ED%94%84%EB%9D%BC%EC%9D%B4%EC%A6%88(Surprise)%EB%A5%BC_%EC%82%AC%EC%9A%A9%ED%95%9C_%EC%B6%94%EC%B2%9C%EC%8B%9C%EC%8A%A4%ED%85%9C(Recommendations)/

pred_df = pd.DataFrame(knnbaseline_predictions_i)
pred_df[(pred_df['uid']==544371892)]

,uid,iid,r_ui,est,details
0,544371892,22700067,0.233333,0.205982,"{'actual_k': 3, 'was_impossible': False}"
32163,544371892,22700069,0.233333,0.218720,"{'actual_k': 2, 'was_impossible': False}"
40299,544371892,22700068,0.233333,0.220167,"{'actual_k': 4, 'was_impossible': False}"

## (2) svd, svdpp (CF) 모델

In [25]:
 ## svd 
 ## 참고: https://surprise.readthedocs.io/en/stable/matrix_factorization.html#matrix-factorization-based-algorithms

svd_algo = SVD()

svd_algo.fit(trainset)
svd_predictions = svd_algo.test(testset)

file_name = 'svd_model'
dump.dump(file_name, algo=svd_algo)
# _, loaded_algo = dump.load(file_name)

accuracy.rmse(svd_predictions)
accuracy.mae(svd_predictions)
print("Done!")

RMSE: 0.2516
MAE:  0.2021
Done!

In [26]:
# matrix factorization/ collaborative filtering(CF)
 ## svd++ model : taking into account implicit ratings 
 ## 참고: https://surprise.readthedocs.io/en/stable/matrix_factorization.html#surprise.prediction_algorithms.matrix_factorization.SVDpp

svdpp_algo = SVDpp()

svdpp_algo.fit(trainset)
svdpp_predictions = svdpp_algo.test(testset)

file_name = 'svdpp_model'
dump.dump(file_name, algo=svdpp_algo)
# _, loaded_algo = dump.load(file_name)

accuracy.rmse(svdpp_predictions)
accuracy.mae(svdpp_predictions)
print("Done!")

RMSE: 0.2365
MAE:  0.1875
Done!

--여기까지 진행됨.

원본 데이터로 진행시 메모리 부족으로 진행이 안되었음.

10만개로 축소하고 진행됨.

## (3) gridsearchCV 모델

In [28]:
from surprise import SVD
from surprise import Dataset
from surprise import Reader
from surprise.model_selection import GridSearchCV

param_grid = {'n_epochs': [5, 20], 'lr_all': [0.002, 0.005],
              'reg_all': [0.4, 0.6]}
              # lr_all – The learning rate for all parameters. Default is 0.005.
              # reg_all – The regularization term for all parameters. Default is 0.02.
              
gs = GridSearchCV(SVDpp, param_grid, measures=['rmse', 'mae'], cv=5) 

reader = Reader()

# The columns must correspond to user id, item id and ratings (in that order).
train_data = Dataset.load_from_df(train_r[['user_id', 'product_id', 'value']], reader)

gs.fit(train_data)

# best RMSE score
print("gs.best_score(rmse): ", gs.best_score['rmse'])

# combination of parameters that gave the best RMSE score
print("gs.best_params: ", gs.best_params['rmse'])

gs.best_score(rmse):  0.5636409335453909
gs.best_params:  {'n_epochs': 5, 'lr_all': 0.002, 'reg_all': 0.4}

In [29]:
from surprise import accuracy

# best model fit 
# We can now use the algorithm that yields the best rmse:
GS_SVDpp_best = gs.best_estimator['rmse']

# retrain on the whole set train
trainset = train_data.build_full_trainset()
GS_SVDpp_best.fit(trainset)

# Compute biased accuracy on train (validation set)
predictions = GS_SVDpp_best.test(trainset.build_testset())
print('validation test,', end='\n')
accuracy.rmse(predictions)
accuracy.mae(predictions)

# 참고:https://surprise.readthedocs.io/en/stable/FAQ.html#how-to-save-some-data-for-unbiased-accuracy-estimation
## 참고: https://surprise.readthedocs.io/en/stable/getting_started.html#train-on-whole-trainset

validation test,
RMSE: 0.5637
MAE:  0.4406

0.44058157643516643

In [30]:

# Compute biased accuracy on train (validation set)
predictions = GS_SVDpp_best.test(testset)
print('testset accuracy,', end='\n')
accuracy.rmse(predictions)
accuracy.mae(predictions)

testset accuracy,
RMSE: 0.5651
MAE:  0.4429

0.4428538942453815

In [35]:
# k-fold trainset, testset 만드는 함수 
from surprise import SVD
from surprise import Dataset
from surprise import Reader
from surprise.model_selection import KFold

reader = Reader()
data = Dataset.load_from_df(df[['user_id', 'product_id', 'value']], reader)

# define a cross-validation iterator
kf = KFold(n_splits=5)

def train_test_get(data, gettype):
  for trainset, testset in kf.split(data):
    if gettype == "train":
      return trainset
    elif gettype == "test":
      return testset 

train_test_get(data, "test")

[(517676026, 26200395, 0.7931034482758621),
 (539464221, 28714424, 0.303030303030303),
 (513447975, 6301259, 0.7),
 (513632293, 1004958, 1.0),
 (512392338, 1002524, 0.7674418604651163),
 (537424879, 19200049, 0.9705882352941176),
 (513005003, 8500122, 0.925925925925926),
 (525457519, 1004777, 0.7777777777777778),
 (512597715, 27700024, 0.0217391304347826),
 (548014274, 37900169, 0.0714285714285714),
 (516379318, 6000248, 0.8205128205128205),
 (534816139, 1004741, 0.75),
 (550284046, 28711793, 0.3734177215189873),
 (512756464, 1004144, 0.9682539682539684),
 (521805127, 1004375, 1.0),
 (543103721, 34200027, 0.369047619047619),
 (513859714, 5301408, 0.8714285714285714),
 (552982808, 5100337, 0.0227272727272727),
 (546241966, 1005033, 0.2),
 (512512173, 26400182, 0.5),
 (513674690, 2702023, 0.1092436974789916),
 (539432849, 2601860, 1.0),
 (513840435, 1004288, 1.0),
 (545070506, 1004659, 1.0),
 (514074741, 8800599, 0.0434782608695652),
 (529408483, 7004322, 0.2),
 (516406369, 47600000, 0.2),
 (512592316, 1004750, 0.3611111111111111),
 (546483424, 3600666, 0.5),
 (513128157, 4800575, 0.6853932584269663),
 (529403889, 12707404, 0.1333333333333333),
 (514759601, 5701036, 0.056),
 (526926727, 5000427, 0.3188405797101449),
 (518395565, 41300089, 0.25),
 (534178501, 1004767, 0.75),
 (550498542, 21400513, 0.96),
 (514701344, 4600469, 0.5970149253731343),
 (548550563, 1003208, 0.4461538461538462),
 (513451334, 1307284, 0.726457399103139),
 (512788937, 1004258, 0.2649572649572649),
 (521448490, 1500470, 0.8928571428571429),
 (519216216, 1004852, 0.5769230769230769),
 (516308445, 8800259, 0.2397260273972602),
 (526975613, 1004655, 1.0),
 (517394303, 1305232, 0.0434782608695652),
 (555477512, 26900008, 1.0),
 (547754346, 1002544, 1.0),
 (513025724, 31300096, 0.5),
 (543059930, 25500026, 0.4545454545454545),
 (541099477, 1004227, 1.0),
 (540244031, 16600209, 0.8),
 (520334483, 32801092, 0.5),
 (540225101, 12201602, 0.1647597254004576),
 (516904134, 8500140, 0.8571428571428571),
 (554965630, 1004856, 1.0),
 (479233261, 1002544, 0.4897959183673469),
 (517982555, 6200885, 0.1290322580645161),
 (515759046, 27300019, 0.1612903225806451),
 (515643918, 16700331, 0.037593984962406),
 (555470075, 30000004, 0.8378378378378378),
 (545730349, 14200410, 0.1558441558441558),
 (515244255, 4801876, 0.3636363636363636),
 (539770477, 4804132, 0.5789473684210527),
 (518124141, 1004249, 0.875),
 (543497280, 2501669, 0.5357142857142857),
 (515603799, 15200271, 0.4285714285714285),
 (538391007, 1002634, 0.9615384615384616),
 (553005738, 17500335, 0.2941176470588235),
 (521339184, 5300481, 0.04),
 (538966365, 8500137, 0.273972602739726),
 (548754644, 49100008, 0.2102803738317757),
 (516215628, 27600026, 0.0484848484848484),
 (533338983, 39500019, 0.8),
 (536149511, 29501428, 0.3846153846153846),
 (552441338, 1005100, 0.905),
 (521118011, 1004246, 0.9490445859872612),
 (533133685, 1004857, 0.7209302325581395),
 (518920654, 11400268, 0.3962264150943396),
 (518733915, 44900092, 0.0555555555555555),
 (555477009, 2800382, 1.0),
 (551998502, 21401822, 0.4090909090909091),
 (513865798, 1005073, 0.6),
 (513053739, 28000023, 0.07773851590106),
 (516904134, 18700026, 0.0476190476190476),
 (555481963, 15200507, 1.0),
 (544602761, 14701015, 0.63),
 (517601951, 28717203, 0.6666666666666666),
 (549497444, 22700094, 0.2222222222222222),
 (521363562, 12700936, 1.0),
 (512962095, 7201765, 0.1935483870967742),
 (527481087, 1004250, 1.0),
 (514281548, 1005105, 0.6785714285714286),
 (551258664, 4200706, 0.2878787878787879),
 (514264448, 10900305, 0.0075757575757575),
 (513093544, 6500699, 0.2268041237113402),
 (544704604, 1003347, 0.373134328358209),
 (514196273, 22700667, 0.0977099236641221),
 (548097220, 1004573, 1.0),
 (532129985, 17301755, 0.1111111111111111),
 (522104702, 1004980, 0.5567010309278351),
 (524115023, 4000137, 0.5789473684210527),
 (555480922, 28710426, 0.3),
 (555350689, 1004741, 0.8252427184466019),
 (513344425, 12706258, 0.2727272727272727),
 (555239136, 1004838, 1.0),
 (555462920, 1003752, 0.9868995633187772),
 (544014345, 3701062, 0.3698630136986301),
 (530691355, 28715855, 0.2903225806451613),
 (555472832, 1003306, 1.0),
 (546238952, 1004856, 1.0),
 (538953772, 26018384, 0.0714285714285714),
 (541481713, 6200284, 0.0434782608695652),
 (547879110, 12704668, 0.2313432835820895),
 (515798108, 3000109, 0.5),
 (516872488, 3200492, 0.9933774834437086),
 (555394812, 1005145, 0.7330316742081447),
 (527002765, 1002524, 0.5),
 (516972343, 12718242, 0.931372549019608),
 (514347752, 2501740, 0.4516129032258064),
 (555376623, 8500249, 1.0),
 (515408832, 6200315, 0.2666666666666666),
 (524141793, 12600037, 1.0),
 (543799355, 5701062, 0.95),
 (551349791, 1004777, 0.9329608938547486),
 (555474888, 5701009, 1.0),
 (512740727, 1004833, 0.75),
 (545805083, 1004449, 0.8611111111111112),
 (512961456, 26400327, 0.6265822784810127),
 (514706098, 6200307, 0.610738255033557),
 (555470148, 26403241, 1.0),
 (514547100, 3801266, 0.2672413793103448),
 (547309187, 5100531, 0.8571428571428571),
 (545368424, 1004870, 0.7272727272727273),
 (513627634, 10502811, 0.1463414634146341),
 (513227490, 26202859, 0.5483870967741935),
 (538488279, 30000132, 1.0),
 (532632283, 9101240, 0.1764705882352941),
 (514926157, 1005003, 0.8620689655172413),
 (544508628, 1004792, 0.8),
 (531063605, 22700776, 0.4895833333333333),
 (503405650, 4000035, 1.0),
 (524152761, 1003317, 0.8958333333333334),
 (531513885, 1800944, 0.1111111111111111),
 (555472476, 1005102, 1.0),
 (548503732, 16300037, 0.125),
 (522104702, 1004648, 0.5567010309278351),
 (513340230, 19200116, 0.16),
 (548554037, 3500243, 0.5333333333333333),
 (531153447, 5000107, 0.0784313725490196),
 (540509896, 15100214, 0.375),
 (554991380, 12706259, 0.2),
 (539859309, 5801218, 0.6666666666666666),
 (555468356, 2601446, 0.8),
 (515898085, 1003307, 0.8688524590163934),
 (518737956, 12701402, 0.3448275862068966),
 (513451334, 1307383, 0.726457399103139),
 (514785981, 21410838, 0.9866666666666668),
 (512970991, 1005156, 0.9879518072289156),
 (541357949, 1307281, 0.7142857142857143),
 (518617024, 1306288, 0.952054794520548),
 (548503732, 28000018, 0.046875),
 (545225043, 1201256, 0.1052631578947368),
 (534455625, 26400265, 0.5961538461538461),
 (547063447, 1005004, 1.0),
 (525254639, 17300785, 1.0),
 (527457100, 1005118, 0.1666666666666666),
 (512540249, 26403098, 0.9247787610619468),
 (555409876, 1005105, 1.0),
 (542758035, 35600012, 0.125),
 (517073292, 16000448, 0.6666666666666666),
 (514946233, 12600013, 0.2553191489361702),
 (513444645, 17303002, 0.064516129032258),
 (523100608, 45300013, 1.0),
 (554598777, 3800979, 0.5555555555555556),
 (555473070, 5100855, 0.125),
 (545497258, 3200573, 0.4285714285714285),
 (554861393, 1002547, 0.9130434782608696),
 (555476339, 1003317, 1.0),
 (539881250, 16001124, 0.574468085106383),
 (555467798, 4300333, 1.0),
 (521573835, 1004858, 0.36),
 (554754734, 1003982, 0.903846153846154),
 (512713188, 2900936, 1.0),
 (549008265, 6801161, 1.0),
 (555475473, 1004807, 1.0),
 (555468338, 38900019, 0.0465116279069767),
 (555468688, 1004856, 1.0),
 (515606787, 15700108, 0.1432748538011695),
 (523729998, 1201297, 1.0),
 (518617024, 1307061, 0.952054794520548),
 (547346377, 1004838, 1.0),
 (531591443, 18700070, 0.2692307692307692),
 (531412278, 3601535, 0.8),
 (555464751, 1004991, 1.0),
 (552938429, 15200519, 0.4166666666666667),
 (555473442, 1003319, 0.5454545454545454),
 (552702317, 1005105, 0.8571428571428571),
 (538449584, 2800424, 0.288),
 (554904551, 5100816, 0.1935483870967742),
 (518878881, 6301054, 0.9444444444444444),
 (523600275, 1004856, 0.75),
 (516615552, 28717654, 1.0),
 (551396573, 8500212, 1.0),
 (518633335, 1802013, 0.0497512437810945),
 (555120207, 16600062, 0.76),
 (512810528, 17301170, 0.0472972972972973),
 (555261826, 5100503, 1.0),
 (514930480, 6000227, 0.4375),
 (555473270, 1004152, 1.0),
 (512584306, 3700777, 0.1304347826086956),
 (542922486, 1307020, 1.0),
 (514526560, 12700931, 0.8095238095238095),
 (516255567, 1004903, 0.6781609195402298),
 (546864448, 5100527, 0.1527777777777778),
 (520680119, 2501075, 0.9),
 (524250869, 3800979, 0.5238095238095238),
 (541091179, 1600362, 1.0),
 (512856016, 1701303, 0.1868131868131868),
 (554394856, 43900058, 0.7517241379310344),
 (547755309, 31501164, 1.0),
 (512686261, 1004210, 0.8095238095238095),
 (541650736, 1005071, 0.8727272727272727),
 (513710899, 1005121, 1.0),
 (533133685, 1004426, 0.7209302325581395),
 (555481382, 1004940, 0.7142857142857143),
 (540950520, 39700102, 1.0),
 (526894348, 1306546, 0.6296296296296297),
 (531906566, 18300927, 1.0),
 (539603127, 1004663, 0.123076923076923),
 (523684628, 7203399, 1.0),
 (520062521, 6200524, 0.4285714285714285),
 (532766354, 4803761, 0.2631578947368421),
 (552062618, 4400038, 0.7162162162162162),
 (517612085, 16500005, 1.0),
 (513995925, 13400277, 0.0769230769230769),
 (519997875, 12709380, 0.25),
 (555464703, 1306949, 0.5625),
 (553377212, 1005160, 1.0),
 (518872547, 5100737, 0.6666666666666666),
 (555468989, 13400117, 0.6666666666666666),
 (512543853, 1003800, 0.2926829268292683),
 (519216216, 1003549, 0.5769230769230769),
 (518807791, 12710241, 0.7272727272727273),
 (515666825, 4804295, 0.1020408163265306),
 (517597867, 2900200, 0.7159090909090909),
 (531197080, 1004256, 1.0),
 (514080146, 22700065, 0.9444444444444444),
 (536415846, 1004833, 1.0),
 (518806710, 1004867, 0.696969696969697),
 (545012370, 2800052, 1.0),
 (515759046, 5100718, 0.7096774193548387),
 (555472304, 1307294, 0.7142857142857143),
 (519372435, 12300489, 0.375),
 (514110874, 1004133, 0.1115241635687732),
 (552221903, 1005115, 0.7857142857142857),
 (544040340, 17300468, 0.0677966101694915),
 (520997323, 2701650, 0.5394736842105263),
 (548703678, 43400011, 0.030716723549488),
 (537459823, 16400025, 0.2222222222222222),
 (555465264, 5100719, 1.0),
 (522531347, 5701025, 0.0763888888888889),
 (518882058, 6200296, 0.3953488372093023),
 (514736099, 3800705, 0.7397260273972602),
 (537455219, 4804056, 0.3571428571428571),
 (555293989, 5100337, 1.0),
 (530289515, 27400036, 1.0),
 (542313933, 12701237, 0.4347826086956521),
 (533223171, 26300502, 1.0),
 (523100327, 44600025, 0.5714285714285714),
 (555462013, 1004873, 1.0),
 (530841105, 1004836, 1.0),
 (514601478, 1004857, 1.0),
 (555476450, 1401577, 1.0),
 (515568049, 3601497, 0.4166666666666667),
 (515461171, 2700618, 0.0718562874251497),
 (525799031, 8500216, 0.2),
 (519181636, 26400634, 0.0482758620689655),
 (516460774, 2200982, 0.1627906976744186),
 (501192468, 1801592, 0.6346153846153846),
 (554395450, 28716931, 1.0),
 (541682559, 16000890, 1.0),
 (550999243, 17200530, 1.0),
 (552779046, 4800236, 0.1678832116788321),
 (555466315, 2601260, 0.4444444444444444),
 (531162076, 15100110, 0.7),
 (522104702, 1004978, 0.5567010309278351),
 (515029784, 42000007, 0.15),
 (534766227, 26202832, 0.8152866242038217),
 (516222435, 1005115, 0.4444444444444444),
 (555466550, 27400032, 0.52),
 (513051834, 12500527, 0.1111111111111111),
 (514727473, 12717166, 1.0),
 (553299462, 11600058, 0.3223593964334705),
 (514629795, 1004957, 0.6666666666666666),
 (516201757, 1004767, 1.0),
 (512452527, 25510254, 0.5454545454545454),
 (547391807, 5300248, 0.4266666666666667),
 (536149511, 29501831, 0.3846153846153846),
 (522971191, 10500843, 0.1666666666666666),
 (514536588, 17300838, 1.0),
 (514376526, 18700010, 0.1818181818181818),
 (526991724, 3600253, 1.0),
 (513414569, 4501567, 0.0558659217877094),
 (555470148, 26401109, 1.0),
 (555468338, 13300378, 0.0697674418604651),
 (538618192, 26201819, 0.9177631578947368),
 (551116663, 5700846, 0.7948717948717948),
 (547322063, 1004767, 0.9285714285714286),
 (514035282, 7203701, 0.5555555555555556),
 (515439708, 39700031, 0.0263157894736842),
 (539412883, 5000240, 0.9215686274509804),
 (555479752, 1306826, 1.0),
 (550835755, 1480524, 0.4285714285714285),
 (535381976, 14701435, 0.75),
 (549666505, 1004957, 0.9666666666666668),
 (544173030, 12702931, 0.0689655172413793),
 (514705573, 12711990, 0.9523809523809524),
 (555477200, 1003305, 0.8823529411764706),
 (555469701, 2702277, 1.0),
 (552408931, 1005104, 0.7647058823529411),
 (545380783, 9600082, 0.6842105263157895),
 (512462186, 2601413, 0.0344827586206896),
 (523277801, 1401872, 0.65),
 (547621956, 26400194, 1.0),
 (542162134, 1004856, 1.0),
 (524497986, 1003441, 0.2711864406779661),
 (513584019, 28717210, 0.1578947368421052),
 (513369847, 5100665, 0.0930232558139534),
 (531197080, 1004250, 1.0),
 (526135014, 26006226, 0.2950819672131147),
 (516246075, 2501558, 0.0754257907542579),
 (541437023, 1004905, 0.8666666666666667),
 (512418831, 1004739, 0.5882352941176471),
 (554217442, 21404140, 0.8529411764705882),
 (555208331, 6301991, 0.0454545454545454),
 (520434202, 10701101, 1.0),
 (549202042, 1004867, 1.0),
 (513187965, 1004806, 0.7807486631016043),
 (551700316, 10800076, 0.4318181818181818),
 (513068622, 1004250, 0.8979591836734694),
 (514432111, 22700299, 1.0),
 (531233959, 8300342, 0.0602409638554216),
 (551359119, 1307067, 1.0),
 (553138090, 7300440, 0.6666666666666666),
 (547466368, 1004935, 0.4133858267716535),
 (529309542, 1201495, 0.1111111111111111),
 (513222093, 15100133, 0.9285714285714286),
 (555466650, 26400193, 1.0),
 (515750335, 5100816, 1.0),
 (512406877, 28400461, 0.5),
 (513805410, 23000433, 0.5950413223140496),
 (555483023, 26402537, 0.1724137931034483),
 (514534397, 6201008, 0.0993914807302231),
 (526013663, 28717447, 0.8),
 (513204639, 2501120, 0.2602040816326531),
 (538645409, 13100411, 1.0),
 (552642467, 5800311, 0.125),
 (555469521, 5300374, 0.0612244897959183),
 (523705997, 1004856, 0.2857142857142857),
 (517906025, 3601000, 1.0),
 (513810851, 26500121, 0.5551948051948052),
 (516414626, 1004749, 0.5066666666666667),
 (513076189, 5100816, 0.2),
 (518636204, 26500130, 0.2038216560509554),
 (555467798, 4300333, 1.0),
 (552941562, 1004249, 0.8525641025641025),
 (513825360, 1004788, 0.9830508474576272),
 (540594582, 1004785, 1.0),
 (512502750, 30000218, 0.0116279069767441),
 (537272007, 1801901, 1.0),
 (513692881, 1801739, 0.3888888888888889),
 (522637243, 46800011, 0.0833333333333333),
 (524504795, 6301811, 0.8125),
 (547146324, 12709740, 0.2982456140350877),
 (555483526, 1004059, 1.0),
 (555212504, 53100015, 0.0869565217391304),
 (527190960, 1005115, 1.0),
 (512867484, 1801710, 0.175438596491228),
 (532511795, 3300349, 1.0),
 (552652462, 12701982, 0.4878048780487805),
 (513215029, 4803186, 0.1428571428571428),
 (522799138, 1004957, 0.9385113268608414),
 (552801092, 7201783, 1.0),
 (517300120, 1004161, 0.8928571428571429),
 (555354172, 1201192, 1.0),
 (539232781, 26200617, 0.825),
 (553633855, 12301125, 0.9767441860465116),
 (536328930, 1004241, 0.987012987012987),
 (514661249, 1480368, 0.352),
 (515016965, 49800000, 0.16),
 (555465928, 1801690, 1.0),
 (515478074, 1004249, 0.5348837209302325),
 (517518911, 15200556, 0.5),
 (529162981, 28000067, 0.2962962962962963),
 (554645126, 1801766, 0.5),
 (518898695, 5600355, 0.6777777777777778),
 (548465420, 12703494, 1.0),
 (512567480, 30000187, 0.2674418604651162),
 (517955467, 13102330, 1.0),
 (555447651, 1004873, 1.0),
 (521245875, 39700051, 0.1123595505617977),
 (550346506, 1004785, 0.3333333333333333),
 (554935393, 2602038, 0.8888888888888888),
 (531938086, 1200947, 0.1034482758620689),
 (555463190, 9700144, 0.7),
 (515397185, 13400209, 0.0789473684210526),
 (555478921, 1002524, 1.0),
 (539770477, 4804177, 0.5789473684210527),
 (512947682, 17301536, 0.2557251908396946),
 (555483172, 1002633, 1.0),
 (512770312, 12718987, 0.3548387096774194),
 (553669125, 17302858, 0.935483870967742),
 (513139583, 3601453, 1.0),
 (516862222, 1004750, 0.1470588235294117),
 (552735111, 1004856, 1.0),
 (548218114, 1004249, 0.4583333333333333),
 (536405743, 12711554, 0.3125),
 (551377651, 1002532, 0.7831325301204819),
 (516411860, 3600666, 0.0957446808510638),
 (540822515, 1801693, 0.2),
 (554387183, 1003304, 1.0),
 (527172522, 12707537, 0.5882352941176471),
 (520226830, 1003769, 0.7727272727272727),
 (530605692, 1002628, 1.0),
 (518768292, 1005124, 0.6666666666666666),
 (515859423, 1500447, 0.2962962962962963),
 (519615334, 13104928, 0.1111111111111111),
 (549034966, 1004903, 1.0),
 (552829049, 8500288, 0.7307692307692307),
 (555474214, 8800446, 0.75),
 (530590577, 1004709, 1.0),
 (534867252, 3300349, 0.0588235294117647),
 (533317425, 1480163, 0.1842105263157894),
 (555394812, 1005135, 0.7330316742081447),
 (516770039, 6200749, 0.1031746031746031),
 (542716320, 1801900, 0.7307692307692307),
 (555474845, 1480391, 1.0),
 (553878920, 26006396, 1.0),
 (554564255, 1003428, 0.9032258064516128),
 (555480928, 1003769, 1.0),
 (543786306, 6300085, 0.925925925925926),
 (518070611, 4600540, 0.9565217391304348),
 (541650736, 1005099, 0.8727272727272727),
 (536658095, 35200044, 0.0555555555555555),
 (516365003, 16100792, 0.1515151515151515),
 (515810692, 23000040, 1.0),
 (513077042, 18400154, 0.25),
 (518503751, 1307188, 1.0),
 (517501418, 1005105, 1.0),
 (545232201, 8500088, 0.2459016393442623),
 (544918244, 1004426, 0.9583333333333334),
 (555162428, 6300680, 0.1176470588235294),
 (524890634, 2701737, 0.1333333333333333),
 (552600989, 6000094, 0.2475247524752475),
 (512736046, 5100689, 0.5581395348837209),
 (524809121, 5701128, 0.4444444444444444),
 (516234410, 1005116, 0.9166666666666666),
 (553876798, 1004792, 0.9891304347826086),
 (519513474, 2800128, 0.8235294117647058),
 (513215935, 22700129, 1.0),
 (533133685, 1005015, 0.7209302325581395),
 (532715546, 2601529, 0.4),
 (555461857, 1004856, 1.0),
 (514060689, 2701588, 0.223175965665236),
 (533700789, 5301323, 0.875),
 (512636421, 1004931, 1.0),
 (533732970, 5100602, 0.5),
 (513746772, 3600661, 0.4),
 (545837297, 28400461, 0.4),
 (549856771, 28718874, 0.054054054054054),
 (552735111, 1004857, 1.0),
 (527893704, 5301150, 0.4583333333333333),
 (553398356, 1002544, 0.2093023255813953),
 (519114091, 4804474, 0.7235772357723578),
 (518337858, 19100247, 1.0),
 (547477164, 19200036, 0.25),
 (547760828, 1004875, 1.0),
 (518898715, 12711216, 0.2631578947368421),
 (555461980, 13101252, 0.2608695652173913),
 (521225023, 15700108, 0.5),
 (512811322, 5100570, 1.0),
 (527011179, 6200523, 0.125),
 (555464386, 1004194, 1.0),
 (551275472, 1005100, 1.0),
 (547263479, 17300355, 0.0833333333333333),
 (555448236, 26300087, 0.734375),
 (535487894, 12710841, 0.5094339622641509),
 (518409248, 5100357, 0.7647058823529411),
 (540244031, 16600093, 0.8),
 (513966349, 26204010, 0.2857142857142857),
 (525234636, 1005115, 0.9836065573770492),
 (512744656, 1002629, 0.7301587301587301),
 (526780925, 12711174, 1.0),
 (525037503, 12714715, 1.0),
 (547099955, 1005132, 1.0),
 (512782238, 5000475, 0.0124481327800829),
 (543429521, 20900065, 0.3235294117647059),
 (514328890, 28718357, 0.0638629283489096),
 (534176490, 1004886, 0.9333333333333332),
 (513254755, 4400226, 0.1678321678321678),
 (542479138, 1801806, 0.3243243243243243),
 (555469986, 1005014, 0.5),
 (555470303, 1004777, 0.4666666666666667),
 (516756960, 10502375, 0.15),
 (548765370, 8500459, 0.4848484848484848),
 (553511205, 22000253, 0.3484848484848485),
 (544003061, 1004258, 0.5102040816326531),
 (513413636, 12710449, 1.0),
 (555481556, 12711055, 1.0),
 (512921121, 21411270, 0.032258064516129),
 (555475295, 10100945, 1.0),
 (555463573, 1307135, 0.5),
 (515437116, 2601306, 0.6666666666666666),
 (517709764, 26403603, 0.1875),
 (526913683, 12716717, 0.8333333333333334),
 (544000492, 1004873, 0.9433962264150944),
 (537134555, 21405753, 0.4444444444444444),
 (554889784, 23300822, 0.4444444444444444),
 (555480122, 1004038, 1.0),
 (515552734, 1004836, 0.859375),
 (553680774, 2600519, 0.2524271844660194),
 (512434124, 12717103, 0.3636363636363636),
 (513879459, 44400079, 0.3333333333333333),
 (512696655, 28716725, 0.125),
 (518450465, 18001420, 0.0077519379844961),
 (527981798, 1003306, 0.8),
 (515326467, 2800207, 0.7142857142857143),
 (533802640, 18000962, 0.0416666666666666),
 (513580377, 34700019, 0.0784313725490196),
 (512686968, 3600263, 0.0242424242424242),
 (530736705, 28719520, 0.3333333333333333),

In [36]:

# testset 
pred_testset = algo_best.test(train_test_get(data, "test"))

NameError: name 'algo_best' is not defined

In [34]:
# cv_results 
results = pd.DataFrame.from_dict(gs.cv_results)
results.T

,0,1,2,3,4,5,6,7
split0_test_rmse,0.564344,0.564344,0.564344,0.564344,0.564344,0.564344,0.564344,0.564344
split1_test_rmse,0.559663,0.559663,0.559663,0.559663,0.559663,0.559663,0.559663,0.559663
split2_test_rmse,0.561857,0.561857,0.561857,0.561857,0.561857,0.561857,0.561857,0.561857
split3_test_rmse,0.562862,0.562862,0.562862,0.562862,0.562862,0.562862,0.562862,0.562862
split4_test_rmse,0.569479,0.569479,0.569479,0.569479,0.569479,0.569479,0.569479,0.569479
mean_test_rmse,0.563641,0.563641,0.563641,0.563641,0.563641,0.563641,0.563641,0.563641
std_test_rmse,0.003292,0.003292,0.003292,0.003292,0.003292,0.003292,0.003292,0.003292
rank_test_rmse,1,2,3,4,5,6,7,8
split0_test_mae,0.440564,0.440564,0.440564,0.440564,0.440564,0.440564,0.440564,0.440564
split1_test_mae,0.436173,0.436173,0.436173,0.436173,0.436173,0.436173,0.436173,0.436173
split2_test_mae,0.439391,0.439391,0.439391,0.439391,0.439391,0.439391,0.439391,0.439391
split3_test_mae,0.43975,0.43975,0.43975,0.43975,0.43975,0.43975,0.43975,0.43975
split4_test_mae,0.44703,0.44703,0.44703,0.44703,0.44703,0.44703,0.44703,0.44703
mean_test_mae,0.440582,0.440582,0.440582,0.440582,0.440582,0.440582,0.440582,0.440582
std_test_mae,0.003553,0.003553,0.003553,0.003553,0.003553,0.003553,0.003553,0.003553
rank_test_mae,1,2,3,4,5,6,7,8
mean_fit_time,1.503913,1.486519,1.485871,1.478752,5.861786,5.861077,5.848569,6.09252
std_fit_time,0.006875,0.015712,0.014678,0.005981,0.013823,0.028759,0.017178,0.242955
mean_test_time,0.20268,0.158878,0.158319,0.157157,0.157727,0.200075,0.158315,0.171342
std_test_time,0.082433,0.003016,0.001482,0.001321,0.001095,0.081236,0.001676,0.019783
params,"{'n_epochs': 5, 'lr_all': 0.002, 'reg_all': 0.4}","{'n_epochs': 5, 'lr_all': 0.002, 'reg_all': 0.6}","{'n_epochs': 5, 'lr_all': 0.005, 'reg_all': 0.4}","{'n_epochs': 5, 'lr_all': 0.005, 'reg_all': 0.6}","{'n_epochs': 20, 'lr_all': 0.002, 'reg_all': 0.4}","{'n_epochs': 20, 'lr_all': 0.002, 'reg_all': 0.6}","{'n_epochs': 20, 'lr_all': 0.005, 'reg_all': 0.4}","{'n_epochs': 20, 'lr_all': 0.005, 'reg_all': 0.6}"
param_n_epochs,5,5,5,5,20,20,20,20
param_lr_all,0.002,0.002,0.005,0.005,0.002,0.002,0.005,0.005
param_reg_all,0.4,0.6,0.4,0.6,0.4,0.6,0.4,0.6

## 1-2) evaluation (knn/svd/svdpp/gridsearchCV 비교)

- knnbaseline (item_based)
- knnbaseline (user_based)
- SVD (CF)
- SVDpp (CF)
- Gridsearch (CF best)
- recall 비교: evaluating_recs.py
- nDCG 개념

### prediction, rmse, mae, precision, recall, f-measure, ndcg_score 계산값

In [ ]:
# predictions 
knn_i_pred = knnbaseline_algo_i.test(testset)
knn_u_pred = knnbaseline_algo_u.test(testset)
svd_pred = svd_algo.test(testset)
svdpp_pred = svdpp_algo.test(testset)
gridCV_svdpp_pred = algo_best.test(testset)

In [ ]:
# test_rmse, test_mae
knn_i_rmse = accuracy.rmse(knn_i_pred)
knn_i_mae = accuracy.mae(knn_i_pred)
knn_u_rmse = accuracy.rmse(knn_u_pred)
knn_u_mae = accuracy.mae(knn_u_pred)
svd_rmse = accuracy.rmse(svd_pred)
svd_mae = accuracy.mae(svd_pred)
svdpp_rmse = accuracy.rmse(svdpp_pred)
svdpp_mae = accuracy.mae(svdpp_pred)
gridCV_svdpp_rmse = accuracy.rmse(gridCV_svdpp_pred)
gridCV_svdpp_mae = accuracy.mae(gridCV_svdpp_pred)

In [ ]:
# recall & precision @ k function
# 참고: https://surprise.readthedocs.io/en/stable/FAQ.html?highlight=recall#how-to-compute-precision-k-and-recall-k

from collections import defaultdict
from surprise import Dataset
from surprise import SVD
from surprise.model_selection import KFold


def precision_recall_at_k(predictions, k, threshold=3.5):
    """Return precision and recall at k metrics for each user"""

    # First map the predictions to each user.
    user_est_true = defaultdict(list)
    for uid, _, true_r, est, _ in predictions:
        user_est_true[uid].append((est, true_r))

    precisions = dict()
    recalls = dict()
    for uid, user_ratings in user_est_true.items():

        # Sort user ratings by estimated value
        user_ratings.sort(key=lambda x: x[0], reverse=True)

        # Number of relevant items
        n_rel = sum((true_r >= threshold) for (_, true_r) in user_ratings)

        # Number of recommended items in top k
        n_rec_k = sum((est >= threshold) for (est, _) in user_ratings[:k])

        # Number of relevant and recommended items in top k
        n_rel_and_rec_k = sum(((true_r >= threshold) and (est >= threshold))
                              for (est, true_r) in user_ratings[:k])

        # Precision@K: Proportion of recommended items that are relevant
        # When n_rec_k is 0, Precision is undefined. We here set it to 0.

        precisions[uid] = n_rel_and_rec_k / n_rec_k if n_rec_k != 0 else 0

        # Recall@K: Proportion of relevant items that are recommended
        # When n_rel is 0, Recall is undefined. We here set it to 0.

        recalls[uid] = n_rel_and_rec_k / n_rel if n_rel != 0 else 0

    return precisions, recalls

In [ ]:
# knn_i 모델 precision&recall
knn_i_prec, knn_i_re = precision_recall_at_k(knn_i_pred, k=5, threshold=4)

# Precision and recall can then be averaged over all users
knn_i_prec_avg = sum(prec for prec in knn_i_prec.values()) / len(knn_i_prec)
print(knn_i_prec_avg)
knn_i_re_avg = sum(rec for rec in knn_i_re.values()) / len(knn_i_re)
print(knn_i_re_avg)

In [ ]:
# knn_u 모델 precision&recall
knn_u_prec, knn_u_re = precision_recall_at_k(knn_u_pred, k=5, threshold=4)

# Precision and recall can then be averaged over all users
knn_u_prec_avg = sum(prec for prec in knn_u_prec.values()) / len(knn_u_prec)
print(knn_u_prec_avg)
knn_u_re_avg = sum(rec for rec in knn_u_re.values()) / len(knn_u_re)
print(knn_u_re_avg)

In [ ]:
# svd precision&recall
svd_prec, svd_re = precision_recall_at_k(svd_pred, k=5, threshold=4)

# Precision and recall can then be averaged over all users
svd_prec_avg = sum(prec for prec in svd_prec.values()) / len(svd_prec)
print(svd_prec_avg)
svd_re_avg = sum(rec for rec in svd_re.values()) / len(svd_re)
print(svd_re_avg)

In [ ]:
# svdpp precision&recall
svdpp_prec, svdpp_re = precision_recall_at_k(svdpp_pred, k=5, threshold=4)

# Precision and recall can then be averaged over all users
svdpp_prec_avg = sum(prec for prec in svdpp_prec.values()) / len(svdpp_prec)
print(svdpp_prec_avg)
svdpp_re_avg = sum(rec for rec in svdpp_re.values()) / len(svdpp_re)
print(svdpp_re_avg)

In [ ]:
# gridCV_svdpp precision&recall

grid_prec, grid_re = precision_recall_at_k(gridCV_svdpp_pred, k=5, threshold=4)

# Precision and recall can then be averaged over all users
grid_prec_avg = sum(prec for prec in grid_prec.values()) / len(grid_prec)
print(grid_prec_avg)
grid_re_avg = sum(rec for rec in grid_re.values()) / len(grid_re)
print(grid_re_avg)

### model별 test_rmse/mae/precision/recall 테이블

In [ ]:
# model별 test prediction  데이터 
# row: Knnbaseline(item based), Knnbaseline(user based), SVD(CF), SVDpp(CF), gridsearch(SVDpp)
# columns: test RMSE, test MAE, test_time, Precision, recall
# hybrid 모델 수치는 SVDpp(CF)모델과 Knnbaseline(item-based)의 평균값. 
test_prediction = pd.DataFrame({"Algorithm": ["KnnBaseline(item-based)" ,  
                                              "KnnBaseline(user-based)", 
                                              "SVD(CF)",
                                              "SVDpp(CF)",
                                              "gridsearch(SVDpp)",
                                              "Hybrid(CF+CBF)"

                                              ]
                                ,"test_rmse": [knn_i_rmse , knn_u_rmse, svd_rmse , svdpp_rmse , gridCV_svdpp_rmse, svdpp_rmse*0.4+knn_i_rmse*0.6]
                                ,"test_mae":[knn_i_mae , knn_u_mae, svd_mae, svdpp_mae , gridCV_svdpp_mae, svdpp_mae*0.4+knn_i_mae*0.6]
                                ,"Precision":[knn_i_prec_avg ,knn_u_prec_avg ,svd_prec_avg ,svdpp_prec_avg , grid_prec_avg, svdpp_prec_avg*0.4+knn_i_prec_avg*0.6]
                                ,"recall":[knn_i_re_avg ,knn_u_re_avg ,svd_re_avg ,svdpp_re_avg ,grid_re_avg, svdpp_re_avg*0.4+knn_i_re_avg*0.6 ]
                                })

test_prediction

## 1-3) 추천목록 비교

- (CF vs Hybrid_latent feature added_model 목록)

(1) 콘텐츠필터링/협업필터링 모델의 top N 추천목록 (※주의: top-n 구하는 코드 시간이 오래걸림)

In [ ]:
# 참고: https://www.fun-coding.org/recommend_basic7.html

# 1안) n=5로 줄여서 진행. 
# 2안) 원데이터 자체를 1만까지 줄여서 진행. 

from collections import defaultdict
from surprise import Dataset
from surprise import accuracy

# top k item list 구하는 함수  
def get_top_n(predictions, n):
    """Return the top-N recommendation for each user from a set of predictions.

    Args:
        predictions(list of Prediction objects): The list of predictions, as
            returned by the test method of an algorithm.
        n(int): The number of recommendation to output for each user. Default
            is 10.

    Returns:
    A dict where keys are user (raw) ids and values are lists of tuples:
        [(raw item id, rating estimation), ...] of size n.
    """

    # First map the predictions to each user.
    top_n = defaultdict(list)
    for uid, iid, true_r, est, _ in predictions:
        top_n[uid].append((iid, est))

    # Then sort the predictions for each user and retrieve the k highest ones.
    for uid, user_ratings in top_n.items():
        user_ratings.sort(key=lambda x: x[1], reverse=True)
        top_n[uid] = user_ratings[:n]

    return top_n

In [ ]:
# svdpp_pred
testset = trainset.build_anti_testset()
# knn_i_pred = knnbaseline_algo_i.test(testset)
svdpp_pred = svdpp_algo.test(testset)

  # 참고: https://surprise.readthedocs.io/en/stable/FAQ.html#how-to-save-some-data-for-unbiased-accuracy-estimation
  # 참고: https://surprise.readthedocs.io/en/stable/algobase.html#surprise.prediction_algorithms.algo_base.AlgoBase.predict
  # 참고: https://surprise.readthedocs.io/en/stable/FAQ.html#what-are-raw-and-inner-ids

svdpp_top_n = get_top_n(svdpp_pred, n=5)

In [ ]:
svdpp_top_n_df = pd.DataFrame(svdpp_top_n)
# knn_i_top_n_df.groupby(by=222811).max()
result = svdpp_top_n_df[222811].values

In [ ]:
svdpp_test = test_r[['user_id', 'item_id', 'rating']][ ( test_r['item_id']==123793 ) | ( test_r['item_id']==138431 ) | ( test_r['item_id']==730008 ) | 
                             ( test_r['item_id']==2918587 ) | ( test_r['item_id']==612756 )]
# knn_test = knn_test[ ( knn_test['user_id']== 222811)]
# knn_test
svdpp_test

In [ ]:
# category, brand를 보고자 한다면 이렇게 따로 볼 수는 있음. 
svdpp_top_n = df_r_m[['product_id','category_code', 'brand']][(df_r_m['product_id'] == 5100816) 
| (df_r_m['product_id'] == 12703498) |(df_r_m['product_id'] == 12703015) |(df_r_m['product_id'] == 22700084)
].drop_duplicates()
# knn_top_n['est'] = top_n
# knn_top_n.groupby(by='item_id').count()
svdpp_top_n.head()

## (2) 📍hybrid(CF(SVDpp)+CBF(Content-Based or Item-Based Filtering)+Item-Similiarity+Popularity)

- (CF+CBF 4:6가중평균합 모델) + (Item-Similarity모델) + (Popularity 모델)을 혼합한 모델.

### (2-1) item similarity 모델 (category기준)
- 하이브리드 모델에 들어갈 Item-Similarity 모델

In [ ]:

category = df_r_m['category_code'].unique().tolist()
category

In [ ]:
category.index('computers.notebook')

In [ ]:
category_r_to_idx = dict()
def addcategory(category):
  for i in category: # category리스트를 돈다
    category_r_to_idx[i] = category.index(i)
  return category_r_to_idx

addcategory(category)

In [ ]:
# idx_to_category_r
  
idx_to_category_r = dict([(value, key) for key, value in category_r_to_idx.items()]) 
idx_to_category_r

In [ ]:
# category vectorizing 
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
tf_new = TfidfVectorizer(analyzer='word', ngram_range=(1, 2), min_df=0, stop_words='english')
tfidf_matrix_new_r = tf_new.fit_transform(df_r_m['category'])

In [ ]:

# category 가 추가된 matrix 의 cosine similarity 계산
cosine_sim_new = linear_kernel(tfidf_matrix_new_r, tfidf_matrix_new_r)

In [ ]:
category_name = df_r_m['category_code']
indices = pd.Series(df_r_m.index, index=df_r_m['category_code'])
indices.head(10)

In [ ]:
indices["top"]

In [ ]:

def get_recommendations_new(category_name):
    
    idx = indices[category_name]
    if type(idx) != np.int64:
        if len(idx)>1:
            print("ALERT: Multiple values")
            idx = idx[0]
    sim_scores = list(enumerate(cosine_sim_new[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    sim_scores = sim_scores[1:11]
    item_indices = [i[0] for i in sim_scores]
    return df_r_m['item_id'].iloc[item_indices]

# get_recommendations_new("top") # 특정 category에 대한 아이템 추천.

### (2-2) popularity 모델 (category기준)
- 하이브리드 모델에 들어갈 popularity 모델

In [ ]:
df_r_m['rating_average'] = df_r_m['rating_average'].astype(int)
df_r_m.dtypes

In [ ]:
# popularity model (popularity = rating_average)
def category_based_popularity(category):
 
    mask = df_r_m.category.apply(lambda x: category in x)
    filtered_item = df_r_m[mask]
    filtered_item = filtered_item.sort_values(by='rating_average', ascending=False)

    return filtered_item['item_id'].head(10).values.tolist() 

category_based_popularity('top')

In [ ]:
def user_top_category(user_id):
    user_id = df_r_m['user_id'][(df_r_m['user_id'] == user_id)].values[0].copy()
    print("User vec: ", user_id)
    top_category_indices = np.flip(np.argsort(user_id))
    category_list = []
    for i in top_category_indices[:3]:
        category_list.append(idx_to_category_r[i])
    return category_list

In [ ]:
user_id = 535871217
# df_r_m['user_id'][(df_r_m['user_id'] == user_id)].values.copy()
df_r_m[(df_r_m['user_id'] == user_id)]

In [ ]:
user_top_category(535871217)